# Zastosuj dopiero gdy repo bedzie wypchniete:
#   kubectl apply -f k3s/argocd/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: na-fali
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:shugopl/na-fali.git
    targetRevision: HEAD
    path: k3s
  destination:
    server: https://kubernetes.default.svc
    namespace: na-fali
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
